language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
  - openjdk11
  - openjdk14
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea
script:
  - mvn -V --no-transfer-progress

after_success:
  - mvn -V --no-transfer-progress clean test jacoco:report coveralls:report -Ptravis-jacoco javadoc:javadoc -Ddoclint=all